[tool.poetry]
name = "lhub_extractors"
version = "0.3.8"
description = "LogicHub Feature Extractors"
authors = ["Bernie Liu <bernie@logichub.com>"]

[tool.poetry.dependencies]
python = ">=3.6"
dataclasses-json = "*"
click = "~7.0"
docstring-parser = "~0.1"
wheel = "^0.32.3"

[tool.poetry.dev-dependencies]
pytest = "^3.0"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
