[tool.poetry]
name = "motto"
version = "0.1.1"
description = "Japanese sentence linter platform for reStructuredText"
authors = ["Kazuya Takei <attakei@gmail.com>"]
license = "Apache-2.0"
readme = "README.rst"

[tool.poetry.dependencies]
python = "^3.6 || ^3.7 || ^3.8"
docutils = "^0.15.2"
click = "^7.0"
janome = "^0.3.10"
typing-extensions = "^3.7.4"
click-default-group = "^1.2.2"
dataclasses = {version = "^0.7", python = ">=3.6,<3.7"}

[tool.poetry.dev-dependencies]
black = "^19.10b0"
mypy = "^0.750"
pytest = "^5.3.2"
pytest-pythonpath = "^0.7.3"
sphinx = "^2.3.0"
doc8 = "^0.8.0"
bumpversion = "^0.5.3"

[tool.poetry.scripts]
motto = "motto.cli:main"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
