[tool.poetry]
name = "letov"
version = "2.1.3"
description = "TripSource logging utilities"
authors = ["BCD Trip tech <development@bcdtriptech.com>"]

[tool.poetry.dependencies]
python = ">=3.6,<3.9"
zstandard = "^0.11.0"
click = "^7.0"
fluent-logger = "^0.9.4"

[tool.poetry.dev-dependencies]
coverage = "^4.5"
flake8 = "^3.7"
flake8-comprehensions = "^2.1"
flake8-docstrings = "^1.3"
flake8-import-order = "^0.18.1"
flake8-quotes = "^1.0"
flake8-sorted-keys = "^0.2.0"
flake8-string-format = "^0.2.3"
ipython = "^7.4"
nose = "^1.3"

[tool.poetry.scripts]
letov = 'letov.cli:cli'

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"

